version: '3'

services:
    nginx:
        container_name: nginx_todo
        image: stenfrank/nginx:1.3
        working_dir: /var/www/html
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/sites-available:/etc/nginx/sites-available
            - ./docker/nginx/conf/uploads-config.conf:/etc/nginx/conf.d/uploads-config.conf
        networks:
            - todolist
        depends_on:
            - php
    php:
        container_name: php_todo
        build:
            context: ./docker/php/
        user: "${APP_USER}"
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - todolist

    database:
        container_name: database_todo
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/etc/mysql/conf.d
            - todolistdbdata:/var/lib/mysql
        restart: always
        command: --max_allowed_packet=268435456
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: todolist
            MYSQL_DATABASE: todolist
            MYSQL_PASSWORD: secret
        networks:
            - todolist

    phpmyadmin:
        container_name: phpmyadmin_todo
        depends_on:
            - database
        image: phpmyadmin
        ports:
            - "${APP_PHPMYADMIN_PORT}:80"
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: secret
            PMA_ABSOLUTE_URI: http://phpmyadmin/phpmyadmin/
        networks:
            - todolist

networks:
    todolist:
        driver: "bridge"

volumes:
    todolistdbdata:
